// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: openeox.proto

package tbd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"signer"
	Schema        string       `protobuf:"bytes,1,opt,name=schema,json=,proto3" json:"signer"`
	Statements    []*Statement `protobuf:"bytes,2,rep,name=statements,proto3" json:"statements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shell) Reset() {
	*x = Shell{}
	mi := &file_openeox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shell) ProtoMessage() {}

func (x *Shell) ProtoReflect() protoreflect.Message {
	mi := &file_openeox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shell.ProtoReflect.Descriptor instead.
func (*Shell) Descriptor() ([]byte, []int) {
	return file_openeox_proto_rawDescGZIP(), []int{0}
}

func (x *Shell) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Shell) GetStatements() []*Statement {
	if x != nil {
		return x.Statements
	}
	return nil
}

type Statement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Core           *Core                  `protobuf:"bytes,1,opt,name=core,proto3" json:"core,omitempty"`
	ProductName    string                 `protobuf:"bytes,2,opt,name=productName,proto3" json:"productName,omitempty"`
	ProductVersion string                 `protobuf:"bytes,3,opt,name=productVersion,proto3" json:"productVersion,omitempty"`
	VendorName     string                 `protobuf:"bytes,4,opt,name=vendorName,proto3" json:"vendorName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Statement) Reset() {
	*x = Statement{}
	mi := &file_openeox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_openeox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_openeox_proto_rawDescGZIP(), []int{1}
}

func (x *Statement) GetCore() *Core {
	if x != nil {
		return x.Core
	}
	return nil
}

func (x *Statement) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Statement) GetProductVersion() string {
	if x != nil {
		return x.ProductVersion
	}
	return ""
}

func (x *Statement) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

type Core struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"signer"
	Schema               string                 `protobuf:"bytes,1,opt,name=schema,json=,proto3" json:"signer"`
	EndOfLife            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_of_life,json=endOfLife,proto3" json:"end_of_life,omitempty"`
	EndOfSecuritySupport *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_of_security_support,json=endOfSecuritySupport,proto3" json:"end_of_security_support,omitempty"`
	EndOfSales           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_of_sales,json=endOfSales,proto3" json:"end_of_sales,omitempty"`
	LastUpdated          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Core) Reset() {
	*x = Core{}
	mi := &file_openeox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Core) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Core) ProtoMessage() {}

func (x *Core) ProtoReflect() protoreflect.Message {
	mi := &file_openeox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Core.ProtoReflect.Descriptor instead.
func (*Core) Descriptor() ([]byte, []int) {
	return file_openeox_proto_rawDescGZIP(), []int{2}
}

func (x *Core) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Core) GetEndOfLife() *timestamppb.Timestamp {
	if x != nil {
		return x.EndOfLife
	}
	return nil
}

func (x *Core) GetEndOfSecuritySupport() *timestamppb.Timestamp {
	if x != nil {
		return x.EndOfSecuritySupport
	}
	return nil
}

func (x *Core) GetEndOfSales() *timestamppb.Timestamp {
	if x != nil {
		return x.EndOfSales
	}
	return nil
}

func (x *Core) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_openeox_proto protoreflect.FileDescriptor

const file_openeox_proto_rawDesc = "" +
	"\n" +
	"\ropeneox.proto\x12\vopeneox.tbd\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\x05Shell\x12\x17\n" +
	"\x06schema\x18\x01 \x01(\tR\a$schema\x126\n" +
	"\n" +
	"statements\x18\x02 \x03(\v2\x16.openeox.tbd.StatementR\n" +
	"statements\"\x9c\x01\n" +
	"\tStatement\x12%\n" +
	"\x04core\x18\x01 \x01(\v2\x11.openeox.tbd.CoreR\x04core\x12 \n" +
	"\vproductName\x18\x02 \x01(\tR\vproductName\x12&\n" +
	"\x0eproductVersion\x18\x03 \x01(\tR\x0eproductVersion\x12\x1e\n" +
	"\n" +
	"vendorName\x18\x04 \x01(\tR\n" +
	"vendorName\"\xab\x02\n" +
	"\x04Core\x12\x17\n" +
	"\x06schema\x18\x01 \x01(\tR\a$schema\x12:\n" +
	"\vend_of_life\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tendOfLife\x12Q\n" +
	"\x17end_of_security_support\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x14endOfSecuritySupport\x12<\n" +
	"\fend_of_sales\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"endOfSales\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdatedB\x98\x01\n" +
	"\x0fcom.openeox.tbdB\fOpeneoxProtoP\x01Z*github.com/carabiner-dev/openeox/types/tbd\xa2\x02\x03OTX\xaa\x02\vOpeneox.Tbd\xca\x02\vOpeneox\\Tbd\xe2\x02\x17Openeox\\Tbd\\GPBMetadata\xea\x02\fOpeneox::Tbdb\x06proto3"

var (
	file_openeox_proto_rawDescOnce sync.Once
	file_openeox_proto_rawDescData []byte
)

func file_openeox_proto_rawDescGZIP() []byte {
	file_openeox_proto_rawDescOnce.Do(func() {
		file_openeox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openeox_proto_rawDesc), len(file_openeox_proto_rawDesc)))
	})
	return file_openeox_proto_rawDescData
}

var file_openeox_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_openeox_proto_goTypes = []any{
	(*Shell)(nil),                 // 0: openeox.tbd.Shell
	(*Statement)(nil),             // 1: openeox.tbd.Statement
	(*Core)(nil),                  // 2: openeox.tbd.Core
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_openeox_proto_depIdxs = []int32{
	1, // 0: openeox.tbd.Shell.statements:type_name -> openeox.tbd.Statement
	2, // 1: openeox.tbd.Statement.core:type_name -> openeox.tbd.Core
	3, // 2: openeox.tbd.Core.end_of_life:type_name -> google.protobuf.Timestamp
	3, // 3: openeox.tbd.Core.end_of_security_support:type_name -> google.protobuf.Timestamp
	3, // 4: openeox.tbd.Core.end_of_sales:type_name -> google.protobuf.Timestamp
	3, // 5: openeox.tbd.Core.last_updated:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_openeox_proto_init() }
func file_openeox_proto_init() {
	if File_openeox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openeox_proto_rawDesc), len(file_openeox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openeox_proto_goTypes,
		DependencyIndexes: file_openeox_proto_depIdxs,
		MessageInfos:      file_openeox_proto_msgTypes,
	}.Build()
	File_openeox_proto = out.File
	file_openeox_proto_goTypes = nil
	file_openeox_proto_depIdxs = nil
}
