# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: go-tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions: {}

jobs:
  go-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      latest: ${{ steps.versions.outputs.GO_MINOR_VERSION_STABLE }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Determine Go versions
      id: versions
      uses: carabiner-dev/actions/go/versions@2a4b2cd115ede14629b03ef7e77586d3269d4c72 # v1.2.3

    - name: Build version matrix
      id: matrix
      run: |
        echo "matrix=[\"${{ steps.versions.outputs.GO_MINOR_VERSION_PREVIOUS }}\",\"${{ steps.versions.outputs.GO_MINOR_VERSION_STABLE }}\"]" >> "$GITHUB_OUTPUT"

  test:
    needs: go-versions
    permissions:
      contents: read

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true

    - name: Test
      run: |
        go get -d ./...
        go test -v ./...
